# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b65bccbb7ef88c7f97e0ef1a4c832e8092feed4a5da401125318172dca3021d4f4c4a6c3d6766f83a90664d204d094cf6d51c1dd201c08d99e78e6093086346

test:
  secret_key_base: 09c33b62c3a756dc706e47a5248ade7346289b4035fe3b872cfec5abc4927593981c381a7404817e354dfdf32b9891d8daef4b4762d5d9097b8dff90734cb2a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
